server {
    listen 80;
    server_name goldstoremultimarcas.com www.goldstoremultimarcas.com;
    client_max_body_size 20M;

    root /var/www/goldstore-frontend; 
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html; # Fundamental para React Router
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|webp|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}